### ISSUE TITLE
Authorize target attr on links

### ISSUE THREAD

**Issue by cedricdelpoux** [remarkjs/remark-html#10]
I, I tried to authorize the `target` attr on my links to enable external links.
So I extends the sanitize schema and use it in `remark-html` options.
I tried to add the target attr with multiple differents syntax (hast, unist, mdast) but my generated html link does not has the `target` attr.

What is wrong whit my source code ? Thank you

```
var remark = require('remark');
var html = require('remark-html');
var select = require("unist-util-select");
var github = require('hast-util-sanitize/lib/github');
var merge = require('deepmerge');
var schema = merge(github, {attributes: {"a": ['target']}});

remark()
  .use(function() {
      return function(ast) {
        select(ast, 'link').forEach(function(node) {
          node.target = "_blank"
          node.data = {
            htmlAttributes: {
              target: '_blank',
            },
            target: '_blank',
          }    
          node.properties = {
            target: '_blank',
          }
        })
      }
  })
  .use(html, {sanitize: schema})
  .process([
    '[Google](https://www.google.com)',
  ]);

// <a href="https://www.google.com">Google</a>

```

**Comment by wooorm** [comment]
Very close! In the case of 'target', you should set 'node.data.hProperties.target'. Nu  need for 'node.target', 'node.properties.target', 'node.data.target', or 'node.data.htmlAttributes.target'!

**Comment by cedricdelpoux** [comment]
Thank you very much !

**Comment by wooorm** [comment]
Cheers! 👋

**Comment by cedricdelpoux** [comment]
If you want this feature too, I created a plugin: https://github.com/xuopled/remark-external-links
👋🏻
