### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by strugee** [remarkjs/remark-html#21]
This project could use a change log.

See http://keepachangelog.com

**Comment by wooorm** [comment]
Hi @strugee! 👋 

I’m all for changelogs, and I used to keep them in the source, but now I’m keeping them at [GH Releases](https://github.com/wooorm/remark-html/releases) (note: I did forget to do the 6.0.0 one, done!)

My reasoning here is that commits are already good logs for getting exactly what changed. For a proper changelog, you need some more editing, and I’d rather do that in a place that’s not kept in source.

Hope that answers your question!

**Comment by strugee** [comment]
Cool, thanks! Filed #22 to eliminate the confusion I ran into here. Absolutely agreed that change logs need more editing, though I'm not sure why that means they can't be kept in the source. I also personally appreciate in-tree change logs because then I can look at it locally in my copy of the npm package but hey - it's your project :)

¯\_(ツ)_/¯

**Comment by wooorm** [comment]
If it’s kept in git, it needs commits to change them (which is kinda weird, a commit updating the list of commits?).
If it’s on npm, it also needs versions (so a changed changelog needs a release).
That feel weird to me. I used to do it fervently, but right now, I’m very happy with GH Releases!

**Comment by strugee** [comment]
> If it’s kept in git, it needs commits to change them (which is kinda weird, a commit updating the list of commits?).

That makes sense, but I think you may be approaching the change log wrong (IMO only, obviously). Remember, [friends don't let friends dump git logs into CHANGELOGs™](http://keepachangelog.com/en/0.3.0/). Personally I treat the change log as documentation, just like README.md. So the entries in my change logs don't always have a 1-to-1 correspondence with commits, not all commits end up in the change log, etc. In that case it actually feels natural to keep documentation (i.e. the change log) alongside source, just like how you keep README.md alongside the source.

> If it’s on npm, it also needs versions (so a changed changelog needs a release).

In theory yes, but in practice I haven't found myself needing to update change logs that often. Besides, having it in the npm package is just for convenience - the canonical location should always be on GitHub, in the same way that people generally consider the canonical location of READMEs to be in the upstream repository.

I should also point out that a lot of people, myself included, expect change logs to be in a file named CHANGELOG.md. Hence this issue.

*That all being said* this is your project, so if you want to close #22 go ahead. I won't be offended :)

**Comment by wooorm** [comment]
That took a while to respond, sorry! 😬

Although I agree with you on more involved projects, I don’t think this is that. For now, I’ll document everything on [GH Releases](https://github.com/wooorm/remark-html/releases).

I do sympathise with needing a changelog though, and hope releases is a good enough place for that. Feel free to call me out if those aren’t good though!

Cheers,
Titus

**Comment by strugee** [comment]
Thanks @wooorm :-)
