### ISSUE TITLE
Backslash is not being converted to html line break 

### ISSUE THREAD

**Issue by alexeychikk** [remarkjs/remark-html#27]
### Subject of the issue
Converting markdown from `pressEventsList.body`:
```md
---
_convertMdFieldToHtml_: pressEventsList.body
pressEventsList:
  - body: |-
      ZIUA CARGO EXHIBITION IN POIAIXA BRASOV 2019\
      The TRUCKNET team in action.
    photo: "https://res.cloudinary.com/trucknet/image/upload/v1575309087/press/08.jpg"
---
```
Results in the following html:
```html
<p>ZIUA CARGO EXHIBITION IN POIAIXA BRASOV 2019The TRUCKNET team in action.</p>
```
As you can see backslash is just ignored.

### Steps to reproduce

https://codesandbox.io/s/vanilla-5w9op

### Expected behaviour

I think `<br>` should be inserted.

### Actual behaviour

Backslash is just removed.

**Comment by wooorm** [comment]
You can [turn on the `commonmark: true` option](https://github.com/remarkjs/remark/tree/master/packages/remark-parse#optionscommonmark), which should fix this.

**Comment by alexeychikk** [comment]
@wooorm Sorry for bothering you but I can't get this to work.
https://codesandbox.io/s/vanilla-5w9op
