### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by yurist38** [remarkjs/remark-html#28]
Hello! How do you feel about re-writing this plugin to TypeScript? It's quite small, so it should be easy to re-implement it in TS. Or if you don't want to have it written in TS, would be great to at least add TS definitions. If need any help with this, please let me know. Thanks!

### Subject of the feature

Support TypeScript

### Problem

The package can't be easily used in TypeScript projects because type definitions are missing.

### Expected behaviour

The package can be used in TS project without any warnings.

### Alternatives

As an alternative, as I said, you can just add TS definitions (.d.ts files)

**Comment by ChristianMurphy** [comment]
There has been some discussion about this at
https://spectrum.chat/unified/general/rewriting-in-typescript~a420b99c-b416-457e-adbd-6f4dbdddf606
and https://spectrum.chat/unified/general/keeping-typescript-definitions-in-respective-repos~e3f49750-acb6-4075-8cbf-4daf072a2286

The current preference is to add typescript definitions to the repository.
We've been going repo by repo adding typings, there are over 300 repos in the unified ecosystem, this is one repo we haven't gotten to yet.
Feel free to open PRs to help move the migrations toward typings forward.

--- 
Also be aware there is a preference to add typings to lower level packages and move up to higher level packages.
For example this repo depends on https://github.com/remarkjs/remark-rehype and https://github.com/rehypejs/rehype/tree/master/packages/rehype-stringify it would be good to ensure we have typings in those dependencies before adding typings here.

PRs are welcome!
