### ISSUE TITLE
Prevent `sanitize`, `handlers` being passed to `hast-util-to-html`

### ISSUE THREAD

**Issue by muescha** [remarkjs/remark-html#34]
## Current Code

Given this code:

https://github.com/remarkjs/remark-html/blob/f59c15d09ab1b94c27d450ead5295acfdfb8d65e/index.js#L11-L14

and the info from readme that this values are used differently:

- Readme (with PR #33)
  > All options **except** for `sanitize` and `handlers` are passed to `hast-util-to-html`.

- `sanitize` => `clean`
  https://github.com/remarkjs/remark-html/blob/f59c15d09ab1b94c27d450ead5295acfdfb8d65e/index.js#L13

- `handlers`
  https://github.com/remarkjs/remark-html/blob/f59c15d09ab1b94c27d450ead5295acfdfb8d65e/index.js#L20

## Problem

should these options not removed from `settings` before forwarding them to `toHtml` to avoid side effects?
https://github.com/remarkjs/remark-html/blob/f59c15d09ab1b94c27d450ead5295acfdfb8d65e/index.js#L20

## Possible Side Effects

the hast `toHtml` also use handlers, and when i expect that this utility also make the handlers also as option (like in mdast https://github.com/syntax-tree/mdast-util-to-hast/pull/10), then there can be side effects:

https://github.com/syntax-tree/hast-util-to-html/blob/4c1d1542808c29cf69e775ae8bda62bf16d3c3c4/lib/one.js#L7-L14

**Comment by wooorm** [comment]
`hast-util-to-html` does not use `handlers` or `sanitize`, so side-effects is currently not an issue, I believe?

**Comment by muescha** [comment]
not just now, but i think this can be added in the feature like in https://github.com/syntax-tree/mdast-util-to-hast/pull/10 then it maybe becomes a problem and because the handlers  for `root` and `text` are in both

**Comment by wooorm** [comment]
Right, although custom `handlers` in hast -> HTML doesn‘t really make sense. I don’t see them being added there. If for some reason they were added, we’d have a problem because they couldn’t be passed from this project, and that would be surfaced by a new issue!
I’m really not worried about any of this happening, and prefer embracing JavaScript’s chill ;)
