### ISSUE TITLE
Classnames for tags

### ISSUE THREAD

**Issue by n1stre** [remarkjs/remark-html#37]
Hello! What do think about adding `classNames` to [`options`](https://github.com/remarkjs/remark-html#options) which will represent an object mapping tag names to classes that would be applied to each corresponding html tags?

### Subject of the feature
Add `classNames` option

### Problem
As far as I can tell there is no easy way to apply classnames to specific html tags.

### Expected behavior
Was thinking about something like:

```javascript
import remark from "remark";
import html from "remark-html";

export async function markdownToHtml(markdown) {
  const result = await remark()
    .use(html, {
      classNames: {
        p: "text-md",
        h1: "text-xl bold",
      },
    })
    .process(markdown);
    
  return result.toString();
}
```

So that when processing markdown with the following content:

```markdown
# Heading

Some paragraph text

Another paragraph text
```

Which will result in:

```html
<h1 class="text-xl bold">Heading</h1>
<p class="text-md">Some paragraph text</p>
<p class="text-md">Another paragraph text</p>
```

### Alternatives
🤷

### Possible implementation

```javascript
'use strict'

var toHast = require('mdast-util-to-hast')
var toHtml = require('hast-util-to-html')
var sanitize = require('hast-util-sanitize')
var tagClassnames = require('hast-util-tag-classnames') // or maybe even make it a part of "hast-util-classnames"

module.exports = plugin

function plugin(options) {
  var settings = options || {}
  // ...
  var classNames = settings.classNames;

  this.Compiler = compiler

  function compiler(node, file) {
    // ...

    if (clean) {
      hast = sanitize(hast, schema)
    }

    if (classNames) {
       hast = tagClassnames(hast, classNames)
    }
    
    // ...
  }
}

```

Where `tagClassnames` is just iterates though every node and applies `className` prop to every corresponding `tagName`s. 
I can proceed to making PRs if this feature sounds reasonable.
Thanks!

**Comment by ChristianMurphy** [comment]
This is where:

> This package essentially packs remark-rehype and rehype-stringify, and although it does support some customisation, it isn’t very pluggable. It’s probably smarter to use remark-rehype directly and benefit from the rehype ecosystem.

comes into play.

A rehype plugin, https://github.com/martypdx/rehype-add-classes, already solves this problem, and with the same syntax as you'd prefer to use.

**Comment by wooorm** [comment]
Closing this as, as the readme notes and Christian points out, this is outside of the scope of this project and solved nicely elsewhere!
