### ISSUE TITLE
[TS]: MDAST util to HAST has no exported member `Handlers`

### ISSUE THREAD

**Issue by mxdvl** [remarkjs/remark-html#39]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-html@15.0.1 + mdast-util-to-hast@12.3.0

### Steps to reproduce

Run `tsc` against the project.

### Expected behavior

The project should compile without errors.

The type declaration of [remark-html](https://unpkg.com/remark-html@15.0.1/index.d.ts) expects [mdast-util-to-hast](https://unpkg.com/mdast-util-to-hast@12.3.0/lib/index.d.ts) to export a `Handlers` type

### Actual behavior

```sh
../node_modules/remark-html/index.d.ts:24:47 - error TS2694: Namespace '"~/repo/node_modules/mdast-util-to-hast/lib/index"' has no exported member 'Handlers'.

24   handlers?: import('mdast-util-to-hast/lib').Handlers | undefined
                                                 ~~~~~~~~


Found 1 error in ../node_modules/remark-html/index.d.ts:24

make: *** [tsc] Error 2
```

### Runtime

Node v14

### Package manager

yarn 1

### OS

macOS

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
Thanks for the report, fixed in [15.0.2](https://github.com/remarkjs/remark-html/releases/tag/15.0.2)!

**Comment by mxdvl** [comment]
That's almost too fast!

**Comment by mxdvl** [comment]
FYI 15.0.2 has not been released to NPM yet.

**Comment by wooorm** [comment]
you’re right, it’s published now!
