### ISSUE TITLE
Allow custom visitors

### ISSUE THREAD

**Issue by sfrdmn** [remarkjs/remark-html#8]
Would be helpful to introduce an API to allow users to specify arbitrary compilers (visitors) for mdast nodes. Right now, `htmlName`, `htmlContent`, etc can be used, but it's pretty awkward when you want to do something more complex (the API is best suited for creating HTML elements without children)

Seems like it may be as simple as `Object.assign(compilers.visitors, options.visitors)`. Alternatively, could add another property `htmlChildren`. The downside of this pattern is added complexity. Here users need to generate some lib-specific data structure, whereas in a custom visitor, they only need to generate an HTML string, which is easily done with pre-existing libraries

**Comment by wooorm** [comment]
Thanks for the Q!

You can extend compilers by modifying `remark.Compiler.visitors`. For example, [`ben-eb/remark-heading-gap`](https://github.com/ben-eb/remark-heading-gap/blob/master/src/index.js).

The `htmlName`, `htmlContent`, `htmlAttributes` feature is for tools which work regardless of compiler (e.g., `remark-vdom`, `remark-html`, `remark-man`, `remark` itself, &c.), for example, by `remark-slug`.

**Comment by sfrdmn** [comment]
Ah, ok cool. Thanks for the clarification :)
